# Mnist Handwriting Digit 

## Importing libraries

In [6]:
import tensorflow
import pandas as pd
from tensorflow.keras.datasets import mnist

In [2]:
print(tensorflow.__version__)

2.0.0


## Loading MNSIT dataset

In [7]:
(train_images,train_labels),(test_images,test_labels) = mnist.load_data()

In [8]:
print(train_images.shape)
train_labels.shape

(60000, 28, 28)


(60000,)

In [9]:
print(len(train_images))
len(train_labels)

60000


60000

In [10]:
print(train_images)
train_labels

[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]


array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [11]:
train_images[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [12]:
train_images[0].ndim

2

In [13]:
train_images[0].shape

(28, 28)

In [14]:
test_images.shape

(10000, 28, 28)

In [15]:
len(test_labels)


10000

In [16]:
test_labels[0]


7

In [17]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [18]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

## The network architecture- Preparing the model

In [20]:
from tensorflow.keras import models
from tensorflow.keras import layers
network = models.Sequential()
network.add(layers.Dense(512, activation='relu', input_shape=(28 * 28,)))
network.add(layers.Dense(10, activation='softmax'))

## Compilation

In [21]:
network.compile(optimizer='rmsprop',loss='categorical_crossentropy',metrics=['accuracy'])

# Normalization

In [22]:
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype('float32') / 255
test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype('float32') / 255


## Preparing the labels(One-hot encoding)

In [23]:
from tensorflow.keras.utils import to_categorical
train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

## Model Training

In [24]:
network.fit(train_images, train_labels, epochs=5, batch_size=128)

Train on 60000 samples
Epoch 1/5
60000/60000 [==============================] - 9s 151us/sample - loss: 0.2534 - accuracy: 0.9266
Epoch 2/5
60000/60000 [==============================] - 6s 102us/sample - loss: 0.1035 - accuracy: 0.9689
Epoch 3/5
60000/60000 [==============================] - 6s 94us/sample - loss: 0.0677 - accuracy: 0.9802
Epoch 4/5
60000/60000 [==============================] - 6s 95us/sample - loss: 0.0489 - accuracy: 0.9852
Epoch 5/5
60000/60000 [==============================] - 6s 106us/sample - loss: 0.0371 - accuracy: 0.9891


## Evaluation

In [25]:
test_loss, test_acc = network.evaluate(test_images, test_labels)

10000/1 [===============================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================

In [26]:
print('test_acc:', test_acc)

test_acc: 0.9821


## Conlusion